
import html
import pandas as pd
import streamlit as st
from config import TEAM_COLORS

def inject_css():
    st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Black+Ops+One&family=Inter:wght@500;700;800;900&family=Rajdhani:wght@600;700&display=swap');
:root{--cream:#f5ead8;--muted:#a99e91;--acid:#d9ff2f;--green:#00ff73;--red:#ff355c;--orange:#ff9900;--line:rgba(245,234,216,.16)}
html,body,[class*="css"]{font-family:Inter,sans-serif}.stApp{background:radial-gradient(circle at 18% 8%,rgba(217,255,47,.16),transparent 25%),radial-gradient(circle at 88% 18%,rgba(255,53,92,.10),transparent 32%),linear-gradient(180deg,#050505 0%,#0b0b09 50%,#050505 100%);color:var(--cream)}
.stApp:before{content:"";position:fixed;inset:0;pointer-events:none;background:linear-gradient(rgba(245,234,216,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(245,234,216,.04) 1px,transparent 1px);background-size:34px 34px;opacity:.8}.block-container{max-width:1240px;padding:1rem 1rem 4rem;position:relative;z-index:1}h1,h2,h3,p,div,span{color:var(--cream)}
.top{position:sticky;top:0;z-index:999;display:flex;justify-content:space-between;align-items:center;background:rgba(5,5,5,.86);border:1px solid var(--line);border-radius:22px;padding:12px 14px;margin-bottom:14px;backdrop-filter:blur(14px)}.brand{display:flex;align-items:center;gap:12px}.mark{width:56px;height:56px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,var(--acid),var(--green));color:#050505;font-family:'Black Ops One';font-size:23px}.brand-title{font-family:'Black Ops One';font-size:25px;line-height:1}.brand-sub{font-family:Rajdhani;color:var(--muted);font-size:13px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase}.status{font-family:Rajdhani;font-weight:700;padding:9px 12px;border-radius:999px;background:rgba(217,255,47,.10);border:1px solid rgba(217,255,47,.28);color:#ecffc1}
.hero{border:1px solid var(--line);border-radius:30px;background:linear-gradient(145deg,rgba(23,22,21,.96),rgba(5,5,5,.98));padding:22px;margin-bottom:16px}.hero h1{font-family:'Black Ops One';font-size:clamp(42px,7vw,82px);line-height:.86;margin:0}.hot{color:var(--acid)}.chip{display:inline-block;margin:6px 6px 0 0;padding:9px 12px;border-radius:999px;border:1px solid var(--line);background:rgba(245,234,216,.055);font-family:Rajdhani;font-weight:700;letter-spacing:.6px;text-transform:uppercase}
.stTabs [data-baseweb="tab-list"]{gap:8px;background:rgba(16,16,15,.86);border:1px solid var(--line);border-radius:18px;padding:8px}.stTabs [data-baseweb="tab"]{border-radius:13px;color:var(--cream);font-family:Rajdhani;font-weight:700;font-size:15px}.stTabs [aria-selected="true"]{background:linear-gradient(90deg,var(--acid),var(--green))!important;color:#050505!important}
.stButton>button{min-height:62px!important;width:100%!important;border:0!important;border-radius:20px!important;font-family:'Black Ops One'!important;font-size:20px!important;color:#050505!important;background:linear-gradient(90deg,var(--acid),var(--green),var(--orange))!important}
.stFileUploader section{background:rgba(245,234,216,.045)!important;border:1px dashed rgba(217,255,47,.35)!important;border-radius:20px!important}[data-testid="stMetric"]{background:rgba(16,16,15,.84);border:1px solid var(--line);border-radius:20px;padding:16px}[data-testid="stMetricValue"]{font-family:'Black Ops One';color:var(--cream)}[data-testid="stMetricLabel"]{color:var(--muted);font-family:Rajdhani;font-weight:700}
.section{display:flex;justify-content:space-between;align-items:center;margin:20px 0 12px}.section h2{font-family:'Black Ops One';font-size:32px;margin:0}.tag{font-family:Rajdhani;font-weight:700;border:1px solid var(--line);background:rgba(245,234,216,.055);border-radius:999px;padding:9px 12px}
.live-wrap{border:1px solid var(--line);border-radius:30px;background:linear-gradient(180deg,rgba(23,22,21,.96),rgba(5,5,5,.98));padding:18px;margin:14px 0;overflow:hidden}.live-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.live-head h3{font-family:'Black Ops One';font-size:30px;margin:0}.live-grid{display:grid;grid-template-columns:1fr .75fr;gap:14px}
.blender-stage{position:relative;height:430px;border-radius:24px;border:1px solid rgba(245,234,216,.12);background:radial-gradient(circle at center,rgba(0,0,0,.45),rgba(0,0,0,.90));overflow:hidden}.blade{position:absolute;left:50%;top:50%;width:265px;height:265px;margin:-132px;border-radius:50%;background:conic-gradient(transparent 0deg,rgba(217,255,47,.88) 34deg,transparent 73deg,rgba(0,255,115,.88) 142deg,transparent 190deg,rgba(255,153,0,.82) 252deg,transparent 312deg);animation:spin 0.95s linear infinite}.center{position:absolute;left:50%;top:50%;width:122px;height:122px;margin:-61px;border-radius:50%;background:#050505;border:2px solid rgba(245,234,216,.28);display:grid;place-items:center;font-family:'Black Ops One';color:var(--acid);z-index:4;text-align:center;font-size:15px}.float-name{position:absolute;font-family:Rajdhani;font-weight:700;font-size:16px;color:var(--cream);background:rgba(245,234,216,.09);border:1px solid rgba(245,234,216,.16);border-radius:999px;padding:7px 10px;z-index:4;animation:orbit 4.8s linear infinite;max-width:160px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.elim{background:rgba(255,53,92,.14);border-color:rgba(255,53,92,.38);color:#ffd9df;animation:flyout 3.8s ease-in-out infinite}.n1{left:7%;top:15%;animation-delay:0s}.n2{right:7%;top:18%;animation-delay:-.7s}.n3{left:10%;bottom:18%;animation-delay:-1.4s}.n4{right:10%;bottom:17%;animation-delay:-2.1s}.n5{left:36%;top:7%;animation-delay:-2.8s}.n6{left:36%;bottom:8%;animation-delay:-3.5s}@keyframes spin{to{transform:rotate(360deg)}}@keyframes orbit{0%{transform:translateY(0) scale(1);opacity:.95}50%{transform:translateY(-24px) scale(.92);opacity:.58}100%{transform:translateY(0) scale(1);opacity:.95}}@keyframes flyout{0%{transform:translateX(0);opacity:1}60%{transform:translateX(32px);opacity:.6}100%{transform:translateX(0);opacity:1}}.machine-feed{position:absolute;left:0;right:0;bottom:0;background:rgba(5,5,5,.90);border-top:1px solid var(--line);height:58px;overflow:hidden;white-space:nowrap}.machine-feed span{display:inline-block;padding:16px 0;font-family:Rajdhani;font-weight:700;letter-spacing:1px;color:#ecffc1;animation:ticker 16s linear infinite}@keyframes ticker{from{transform:translateX(100%)}to{transform:translateX(-100%)}}.live-panel{border:1px solid var(--line);border-radius:24px;background:rgba(16,16,15,.72);padding:14px}.big-count{font-family:'Black Ops One';font-size:52px;line-height:.9;color:var(--acid)}.count-label{font-family:Rajdhani;font-weight:700;color:var(--muted);text-transform:uppercase}.alert{border:1px solid rgba(255,53,92,.35);background:rgba(255,53,92,.10);border-radius:18px;padding:12px;margin-top:10px;font-family:Rajdhani;font-weight:700;color:#ffd9df}.ok{border:1px solid rgba(0,255,115,.26);background:rgba(0,255,115,.08);border-radius:18px;padding:12px;margin-top:10px;font-family:Rajdhani;font-weight:700;color:#d9ffe8}
.card{position:relative;overflow:hidden;min-height:282px;border-radius:26px;border:1px solid var(--line);padding:18px;background:linear-gradient(180deg,rgba(23,22,21,.96),rgba(6,6,6,.98));box-shadow:0 18px 48px rgba(0,0,0,.35)}.card:before{content:"";position:absolute;inset:0 0 auto 0;height:6px;background:linear-gradient(90deg,var(--acid),var(--green),var(--orange))}.card.fire{box-shadow:0 0 36px rgba(255,153,0,.22),0 18px 48px rgba(0,0,0,.45)}.card.fire:after{content:"🔥 FIRE";position:absolute;right:18px;top:18px;color:#ffcc75;font-family:Rajdhani;font-weight:700}.role{display:inline-block;font-family:Rajdhani;font-weight:700;text-transform:uppercase;border:1px solid var(--line);border-radius:999px;padding:7px 10px;background:rgba(245,234,216,.055)}.player{font-family:'Black Ops One';font-size:29px;line-height:1.05;margin:14px 0 4px}.meta{font-family:Rajdhani;color:var(--muted);font-weight:700;font-size:15px;min-height:38px}.score{font-family:'Black Ops One';font-size:42px}.score small{display:block;font-family:Rajdhani;color:var(--muted);font-size:12px}.ring{height:12px;background:rgba(245,234,216,.09);border-radius:999px;overflow:hidden;margin-top:8px}.fill{height:100%;background:linear-gradient(90deg,var(--acid),var(--green),var(--orange));border-radius:999px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.stat{border:1px solid rgba(245,234,216,.10);background:rgba(245,234,216,.045);border-radius:14px;padding:9px}.stat b{display:block}.stat span{font-family:Rajdhani;color:var(--muted);font-size:11px;text-transform:uppercase;font-weight:700}.badge{display:inline-block;margin:10px 5px 0 0;padding:6px 8px;border-radius:999px;background:rgba(217,255,47,.10);border:1px solid rgba(217,255,47,.24);font-family:Rajdhani;font-weight:700;color:#ecffc1}.audit-good{border:1px solid rgba(0,255,115,.28);background:rgba(0,255,115,.08);border-radius:16px;padding:12px;color:#d9ffe8}.audit-bad{border:1px solid rgba(255,53,92,.35);background:rgba(255,53,92,.10);border-radius:16px;padding:12px;color:#ffd9df}
.feed-box{background:rgba(16,16,15,.86);border:1px solid var(--line);border-radius:22px;padding:12px}.feed-row{font-family:Rajdhani;padding:10px;border-bottom:1px solid rgba(245,234,216,.08)}.feed-row:last-child{border-bottom:0}.cut{color:var(--red);font-weight:700}.alive{color:var(--green);font-weight:700}.gate{color:var(--acid);font-weight:700}
.ticket-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px}.ticket{border:1px solid var(--line);border-radius:24px;background:linear-gradient(180deg,rgba(23,22,21,.96),rgba(6,6,6,.98));padding:18px}.ticket h3{font-family:'Black Ops One';font-size:30px;margin:0 0 12px}.leg{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid rgba(245,234,216,.1);padding:12px 0;font-family:Rajdhani;font-weight:700}.odds{background:rgba(217,255,47,.10);border:1px solid rgba(217,255,47,.24);border-radius:10px;padding:6px 9px;color:#ecffc1}.lock{margin-top:14px;padding:14px;border-radius:16px;background:linear-gradient(90deg,var(--acid),var(--green));color:#050505;font-family:'Black Ops One';text-align:center}
</style>""", unsafe_allow_html=True)

def team_color(team):
    t=str(team).lower()
    for k,v in TEAM_COLORS.items():
        if k in t: return v
    return "#d9ff2f"

def fmt(x):
    if x is None or pd.isna(x): return "—"
    return f"{x:.1f}" if isinstance(x,float) else str(x)

def pct(x):
    try: return max(2,min(100,int(float(x or 0))))
    except Exception: return 0

def top_shell():
    st.markdown("""
<div class="top"><div class="brand"><div class="mark">BH</div><div><div class="brand-title">THE BLENDER</div><div class="brand-sub">LOCK ROOM</div></div></div><div class="status">SYSTEM ARMED</div></div>
<div class="hero"><h1>THE <span class="hot">BLENDER</span><br/>LOCK ROOM</h1><span class="chip">OFFICIAL 0 → 18</span><span class="chip">10.5 SEQUENCED</span><span class="chip">ONE OWNER PER GAME</span><span class="chip">NO REVIVALS</span></div>
""", unsafe_allow_html=True)

def live_blender(names=None, cut_names=None, owner="OWNER", status="DATA IN → GATES SPIN → OWNER LOCKED"):
    names=names or ["Upload Slate","Run Machine","Owners Lock","Core Builds"]
    cut_names=cut_names or []
    n=(names+names+names)[:4]+(cut_names+cut_names)[:2]
    html_names=""
    for i,name in enumerate(n[:6]):
        cls=f"float-name n{i+1}" + (" elim" if i>=4 else "")
        html_names += f"<div class='{cls}'>{html.escape(str(name))}</div>"
    st.markdown(f"""<div class="live-wrap"><div class="live-head"><h3>LIVE BLENDER WHEEL</h3><span class="tag">REAL PLAYER FEED</span></div><div class="live-grid"><div class="blender-stage"><div class="blade"></div><div class="center">{html.escape(str(owner))[:18]}</div>{html_names}<div class="machine-feed"><span> MACHINE SPEAKS: {html.escape(status)} </span></div></div><div class="live-panel"><div class="count-label">Survivor Count</div><div class="big-count">{len(names)}</div><div class="ok">LOCK CONFIRMED only after gate sequence.</div><div class="alert">WHO EVENT DETECTED when chaos/transfer role survives.</div><div class="alert">PUBLIC OVEREXPOSURE ALERT checked at Gate 10.</div></div></div></div>""", unsafe_allow_html=True)

def player_card(r):
    p=pct(r.get("score"))
    fire=" fire" if p>=75 else ""
    color=team_color(r.get("team",""))
    st.markdown(f"""<div class="card{fire}" style="border-color:{color}88"><span class="role">{r.get('role','Primary')}</span><div class="player">{r.get('player','')}</div><div class="meta"><span style="color:{color};font-weight:900">{r.get('team','')}</span> vs {r.get('pitcher','')} · Slot {fmt(r.get('lineup_slot'))}</div><div class="score">{fmt(r.get('score'))}<small>TRUE BLEND SCORE</small></div><div class="ring"><div class="fill" style="width:{p}%"></div></div><div class="stats"><div class="stat"><b>{fmt(r.get('pull_pct'))}</b><span>Pull</span></div><div class="stat"><b>{fmt(r.get('pitch_edge'))}</b><span>Pitch</span></div><div class="stat"><b>{fmt(r.get('dmg'))}</b><span>DMG</span></div><div class="stat"><b>{fmt(r.get('hr_pa'))}</b><span>HR/PA</span></div><div class="stat"><b>{fmt(r.get('hpi'))}</b><span>HPI</span></div><div class="stat"><b>{fmt(r.get('sweet_spot_pct'))}</b><span>Sweet</span></div></div><span class="badge">CONF {p}%</span><span class="badge">NO REVIVAL</span></div>""", unsafe_allow_html=True)
