
import html
import pandas as pd
import streamlit as st
from config import TEAM_COLORS

def team_color(team):
    t=str(team).lower()
    for k,v in TEAM_COLORS.items():
        if k in t: return v
    return "#d9ff2f"
def fmt(x):
    if x is None or pd.isna(x): return "—"
    return f"{x:.1f}" if isinstance(x,float) else str(x)
def pct(x):
    try: return max(2,min(100,int(float(x or 0))))
    except: return 0

def inject_css():
    st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Black+Ops+One&family=Inter:wght@600;800;900&family=Rajdhani:wght@700&display=swap');
:root{--cream:#f5ead8;--muted:#a99e91;--acid:#d9ff2f;--green:#00ff73;--red:#ff355c;--orange:#ff9900;--line:rgba(245,234,216,.16)}
.stApp{background:radial-gradient(circle at 18% 8%,rgba(217,255,47,.16),transparent 25%),linear-gradient(180deg,#050505,#0b0b09,#050505);color:var(--cream)}
.stApp:before{content:"";position:fixed;inset:0;pointer-events:none;background:linear-gradient(rgba(245,234,216,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(245,234,216,.04) 1px,transparent 1px);background-size:34px 34px}
.block-container{max-width:1180px;padding:1rem 1rem 4rem}.top{display:flex;justify-content:space-between;align-items:center;background:rgba(5,5,5,.86);border:1px solid var(--line);border-radius:22px;padding:12px 14px;margin-bottom:14px}.brand{display:flex;gap:12px;align-items:center}.mark{width:56px;height:56px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,var(--acid),var(--green));color:#050505;font-family:'Black Ops One';font-size:23px}.brand-title,.hero h1,.section h2,.player,.score{font-family:'Black Ops One'}.brand-sub,.status,.chip,.tag,.meta,.stat span,.badge{font-family:Rajdhani}.status{padding:9px 12px;border-radius:999px;background:rgba(217,255,47,.10);border:1px solid rgba(217,255,47,.28);color:#ecffc1}
.hero{border:1px solid var(--line);border-radius:30px;background:linear-gradient(145deg,rgba(23,22,21,.96),rgba(5,5,5,.98));padding:22px;margin-bottom:16px}.hero h1{font-size:clamp(42px,7vw,82px);line-height:.86;margin:0}.hot{color:var(--acid)}.chip{display:inline-block;margin:6px 6px 0 0;padding:9px 12px;border-radius:999px;border:1px solid var(--line);background:rgba(245,234,216,.055)}
.stTabs [data-baseweb="tab-list"]{gap:8px;background:rgba(16,16,15,.86);border:1px solid var(--line);border-radius:18px;padding:8px}.stTabs [aria-selected="true"]{background:linear-gradient(90deg,var(--acid),var(--green))!important;color:#050505!important}.stButton>button{min-height:62px!important;width:100%!important;border:0!important;border-radius:20px!important;font-family:'Black Ops One'!important;font-size:20px!important;color:#050505!important;background:linear-gradient(90deg,var(--acid),var(--green),var(--orange))!important}
.live-wrap{border:1px solid var(--line);border-radius:28px;background:linear-gradient(180deg,rgba(23,22,21,.96),rgba(5,5,5,.98));padding:18px;margin:14px 0}.live-head{display:flex;justify-content:space-between;align-items:center}.live-head h3{font-family:'Black Ops One';font-size:28px}.tag{border:1px solid var(--line);border-radius:999px;padding:9px 12px}.blender-stage{position:relative;height:320px;border-radius:24px;border:1px solid rgba(245,234,216,.12);background:radial-gradient(circle at center,rgba(0,0,0,.45),rgba(0,0,0,.90));overflow:hidden}.blade{position:absolute;left:50%;top:50%;width:240px;height:240px;margin:-120px;border-radius:50%;background:conic-gradient(transparent 0deg,rgba(217,255,47,.88) 34deg,transparent 73deg,rgba(0,255,115,.88) 142deg,transparent 190deg,rgba(255,153,0,.82) 252deg,transparent 312deg);animation:spin .95s linear infinite}.center{position:absolute;left:50%;top:50%;width:110px;height:110px;margin:-55px;border-radius:50%;background:#050505;border:2px solid rgba(245,234,216,.28);display:grid;place-items:center;font-family:'Black Ops One';color:var(--acid);z-index:4}.float-name{position:absolute;font-family:Rajdhani;font-size:14px;color:var(--cream);background:rgba(245,234,216,.09);border:1px solid rgba(245,234,216,.16);border-radius:999px;padding:7px 10px;z-index:4;animation:orbit 4.8s linear infinite;max-width:150px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.n1{left:7%;top:15%}.n2{right:7%;top:18%}.n3{left:10%;bottom:18%}.n4{right:10%;bottom:17%}.n5{left:36%;top:7%}.n6{left:36%;bottom:8%}@keyframes spin{to{transform:rotate(360deg)}}@keyframes orbit{50%{transform:translateY(-24px) scale(.92);opacity:.58}}.machine-feed{position:absolute;left:0;right:0;bottom:0;background:rgba(5,5,5,.90);height:50px;overflow:hidden}.machine-feed span{display:inline-block;padding:14px 0;font-family:Rajdhani;color:#ecffc1;animation:ticker 16s linear infinite;white-space:nowrap}@keyframes ticker{from{transform:translateX(100%)}to{transform:translateX(-100%)}}
.section{display:flex;justify-content:space-between;align-items:center;margin:20px 0 12px}.card{position:relative;min-height:282px;border-radius:26px;border:1px solid var(--line);padding:18px;background:linear-gradient(180deg,rgba(23,22,21,.96),rgba(6,6,6,.98));margin-bottom:14px}.card:before{content:"";position:absolute;inset:0 0 auto 0;height:6px;background:linear-gradient(90deg,var(--acid),var(--green),var(--orange))}.role{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:7px 10px}.player{font-size:29px;margin:14px 0 4px}.meta{color:var(--muted);font-size:15px}.score{font-size:42px}.score small{display:block;color:var(--muted);font-family:Rajdhani;font-size:12px}.ring{height:12px;background:rgba(245,234,216,.09);border-radius:999px;overflow:hidden}.fill{height:100%;background:linear-gradient(90deg,var(--acid),var(--green),var(--orange))}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.stat{border:1px solid rgba(245,234,216,.10);background:rgba(245,234,216,.045);border-radius:14px;padding:9px}.badge{display:inline-block;margin:10px 5px 0 0;padding:6px 8px;border-radius:999px;background:rgba(217,255,47,.10);border:1px solid rgba(217,255,47,.24);color:#ecffc1}.audit-good{border:1px solid rgba(0,255,115,.28);background:rgba(0,255,115,.08);border-radius:16px;padding:12px}.audit-bad{border:1px solid rgba(255,53,92,.35);background:rgba(255,53,92,.10);border-radius:16px;padding:12px}.ticket,.feed-box{border:1px solid var(--line);border-radius:24px;background:rgba(16,16,15,.86);padding:18px}.leg{display:flex;justify-content:space-between;border-bottom:1px solid rgba(245,234,216,.1);padding:12px 0}.odds{background:rgba(217,255,47,.10);border:1px solid rgba(217,255,47,.24);border-radius:10px;padding:6px 9px;color:#ecffc1}.lock{margin-top:14px;padding:14px;border-radius:16px;background:linear-gradient(90deg,var(--acid),var(--green));color:#050505;text-align:center}
</style>""", unsafe_allow_html=True)

def top_shell():
    st.markdown("""<div class="top"><div class="brand"><div class="mark">BH</div><div><div class="brand-title">THE BLENDER</div><div class="brand-sub">LOCK ROOM</div></div></div><div class="status">SYSTEM ARMED</div></div><div class="hero"><h1>THE <span class="hot">BLENDER</span><br/>LOCK ROOM</h1><span class="chip">OFFICIAL 0 → 18</span><span class="chip">10.5 SEQUENCED</span><span class="chip">ONE OWNER PER GAME</span><span class="chip">NO REVIVALS</span></div>""", unsafe_allow_html=True)

def live_blender(names=None, cut_names=None, owner="READY", status="UPLOAD SLATE → FEEDER LOCK → RUN"):
    names=names or ["Upload Slate","Feed PDF","Lock Data","Run Machine"]
    n=(names+names+names)[:6]
    html_names="".join([f"<div class='float-name n{i+1}'>{html.escape(str(nm))}</div>" for i,nm in enumerate(n)])
    st.markdown(f"""<div class="live-wrap"><div class="live-head"><h3>BLENDER MACHINE</h3><span class="tag">PRIVATE FEED</span></div><div class="blender-stage"><div class="blade"></div><div class="center">{html.escape(str(owner))[:18]}</div>{html_names}<div class="machine-feed"><span>{html.escape(status)}</span></div></div></div>""", unsafe_allow_html=True)

def player_card(r):
    p=pct(r.get("score")); color=team_color(r.get("team",""))
    st.markdown(f"""<div class="card" style="border-color:{color}88"><span class="role">{r.get('role','Primary')}</span><div class="player">{r.get('player','')}</div><div class="meta"><span style="color:{color};font-weight:900">{r.get('team','')}</span> vs {r.get('pitcher','')} · Slot {fmt(r.get('lineup_slot'))}</div><div class="score">{fmt(r.get('score'))}<small>TRUE BLEND SCORE</small></div><div class="ring"><div class="fill" style="width:{p}%"></div></div><div class="stats"><div class="stat"><b>{fmt(r.get('pull_pct'))}</b><span>Pull</span></div><div class="stat"><b>{fmt(r.get('pitch_edge'))}</b><span>Pitch</span></div><div class="stat"><b>{fmt(r.get('dmg'))}</b><span>DMG</span></div><div class="stat"><b>{fmt(r.get('hr_pa'))}</b><span>HR/PA</span></div><div class="stat"><b>{fmt(r.get('hpi'))}</b><span>HPI</span></div><div class="stat"><b>{fmt(r.get('sweet_spot_pct'))}</b><span>Sweet</span></div></div><span class="badge">CONF {p}%</span><span class="badge">NO REVIVAL</span></div>""", unsafe_allow_html=True)
